### ISSUE TITLE
The request signature we calculated does not match the signature you provided. Check your secret access key and signing method.

### ISSUE THREAD

**Issue by isshwar** [sidbai/ngx_http_aws_sigv4_request_module#1] opened 2021-02-15 16:23 UTC
Hi Sidbai,

Thanks for creating the module. 

But i could not get to the bucket. followed strictly the instructions but not sure what I been missing. 

<Error>
<Code>SignatureDoesNotMatch</Code>
<Message>The request signature we calculated does not match the signature you provided. Check your secret access key and signing method.</Message>
<Resource>null/null</Resource>
</Error>

Anything that you may point to me to.

Thanks
Eswar

**Comment by sidbai** [comment] 2022-01-24 19:35
Hi Eswar,

Sorry to get back to you late. Is the issue resolved? If not, can you provide more error info?

Thanks

**Comment by aaronhurt** [comment] 2022-08-18 00:02
We have a similar issue that I think is caused by how the parameters are being sorted. Looking at the Sigv4 requirements here: https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html

When query parameter names are duplicated they should be sorted by name and value: https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html
>Sort the parameter names by character code point in ascending order. Parameters with duplicate names should be sorted by value. For example, a parameter name that begins with the uppercase letter F precedes a parameter name that begins with a lowercase letter b.

We have a case where a string with duplicate URL parameters can break the signature calculation and cause the API Gateway to reject the request. Simple example:

Breaks ...
```
thing=222&thing=111
```

Works ...
```
thing=111&thing=222
```

Since the code is only sorting by parameter name it doesn't change these and the request is rejected upstream.

**Comment by isdaves** [comment] 2022-08-18 03:40
Any updates here? This bug is impacting us as well.

**Comment by sidbai** [comment] 2022-08-18 04:06
Hi @leprechau and @isdaves ,

Thank you for reporting this issue. If you have a potential fix, feel free to send a PR. I am more than happy to review and merge. Otherwise, I will try to prioritize the fix in 2022/09, but no guarantee.

Thanks,
Sid

**Comment by aaronhurt** [comment] 2022-08-18 17:20
Created a PR, not sure why it didn't link here: https://github.com/sidbai/ngx_http_aws_sigv4_request_module/pull/3

**Comment by sidbai** [comment] 2022-08-18 17:45
@leprechau Thank you for the fix! PR lgtm, merged!

**Comment by sidbai** [comment] 2022-08-18 18:22
@leprechau Sorry I re-opened the issue.
- https://github.com/sidbai/ngx_http_aws_sigv4_request_module/pull/3/files#diff-2eeab0c9155632375a5588173a5988f923a457efb4fbdbdd731be67cd084849bR26 it is better to use strncmp for the equal check, in case if the char* is not null terminated, which happens in ngx.
- https://github.com/sidbai/ngx_http_aws_sigv4_request_module/pull/3/files#diff-2eeab0c9155632375a5588173a5988f923a457efb4fbdbdd731be67cd084849bR27 here we need to use the value's len, not the key's len for the compare.

**Comment by aaronhurt** [comment] 2022-08-18 18:33
Yes, fair point on strncmp and good catch on the value vs key, thank you!

**Comment by aaronhurt** [comment] 2022-08-18 20:59
New PR with the suggested fixes -> https://github.com/sidbai/ngx_http_aws_sigv4_request_module/pull/4

**Comment by sidbai** [comment] 2022-08-18 21:24
Fix merged

**Closed as completed by sidbai** 2022-08-18 21:24 UTC
